DB: PCaG.ESB.TechPackage.DB

Type: sql

SELECT
	F.CPS_SYS_NAME AS NAME,
	F.CPS_SERVICE_KEY AS PASSWORD,
	F.SAP_COMP_NO AS COMP_NO,
	F.FACT_NO,
	A.ASN_NO,
	B.ASN_ITEM,
	NVL(*TRF_STATUS*, 'C') AS TRF_STATUS,
	A.ARRIVAL_TYPE,
	B.BL_NO,
	A.SHIP_TYPE,
	B.EXT_DEV_NO,
	B.INV_NO,
	B.INV_ITEM,
	B.MAT_NM_INV AS INV_DES,
	B.INV_DATE,
	B.EXP_ARR_DATE,
	V.LIFNR AS SUP_NO,
	B.PURD_NO,
	B.PURD_ITEM,
	B.MAT_NO,
	M.MAT_CD AS MAT_NAME,
	M.SCM_BCLASS_NO,
	M.SCM_MCLASS_NO,
	B.GOODS_KIND,
	NVL(B.SKEP, '') AS SKEP,
	B.PURD_QTY,
	(B.ARR_QTY + B.FOC_QTY) AS ARR_QTY,
	B.FOC_QTY,
	M.UNIT AS UNIT,
	B.PRICE,
	B.ITEM_AMT,
	P.PUNIT_CD AS CURRENCY,
	B.NET_WEIGHT,
	B.WEIGHT_UNIT,
	B.GROSS_WEIGHT,
	B.PIECES,
	B.PACKAGE_WAY,
	B.ORIGIN,
	'SAMPLE_REC' AS TRF_USER,
	TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS') AS TRF_TIME
FROM
	Y_ASN_M A
INNER JOIN Y_ASN_D B ON
	A.FACT_NO = B.FACT_NO
	AND A.ASN_NO = B.ASN_NO
INNER JOIN Y3_FACT F ON
	A.FACT_NO = F.FACT_NO
INNER JOIN AB_VENDER V ON
	A.VENDER_NO = V.VENDER_NO
INNER JOIN Y3_MATM M ON
	B.MAT_NO = M.MAT_NO
INNER JOIN Y3_BASIC_PUNIT P ON
	A.INV_CURRENCY = P.PUNIT
LEFT JOIN UNITS U ON
	U.CH_UNIT = M.UNIT
WHERE
    A.FACT_NO = *FACT_NO*
	AND A.ASN_NO = *ASN_NO*
	AND ((*TRF_STATUS* = 'C' AND NVL(A.CES_STATUS, 'N') <> 'S')
	    OR (*TRF_STATUS* = 'D' AND NVL(A.CES_STATUS, 'N') = 'S'))
	AND V.LIFNR IS NOT NULL
