DB: PCaG.ESB.TechPackage.DB

Type: sql

SELECT
	F.CPS_SYS_NAME AS NAME,
	F.CPS_SERVICE_KEY AS PASSWORD,
	F.SAP_COMP_NO AS COMP_NO,
	F.FACT_NO,
	A.ASN_NO
FROM
	Y_ASN_M A
INNER JOIN Y3_FACT F ON
	A.FACT_NO = F.FACT_NO
WHERE
    F.SAP_COMP_NO = *COMP_NO* 
	AND A.FACT_NO = *FACT_NO*
	AND A.ASN_NO = *ASN_NO*