DB: PCaG.ESB.TechPackage.DB

Type: sql

UPDATE
	Y_CPS_BC
SET
	CLOSE_DATE = *CLOSE_DATE*,
	DECR_STATUS = *DECR_STATUS*,
	DECR_TYPE = *DECR_TYPE*,
	DECR_NO = *DECR_NO*,
	DECR_ITEM = *DECR_ITEM*,
	DECR_DATE = *DECR_DATE*,
	AJU_NO = *AJU_NO*,
	SUP_NO = *SUP_NO*,
	INV_NO = *INV_NO*,
	INV_ITEM = *INV_ITEM*,
	INV_DATE = *INV_DATE*,
	DECR_AMT_FOB = *DECR_AMT_FOB*,
	DECR_AMT_CIF = *DECR_AMT_CIF*,
	CURRENCY = *CURRENCY*,
	TRF_TIME = *TRF_TIME*,
	TRF_USER = *TRF_USER*
WHERE
	COMP_NO = *COMP_NO*
	AND FACT_NO = *FACT_NO*
	AND FORM_TYPE = *FORM_TYPE*
	AND FORM_NO = *FORM_NO*
	AND FORM_ITEM = *FORM_ITEM*